#配置端口号及访问路径
server:
  port: 8090
  servlet:
    context-path: /demo

management:
  security:
    #是否启用安全
    enabled: true
  #springboot 2.0以上版本默认暴露health和info，其它的需要添加以下代码进行暴露
  endpoints:
    web:
      exposure:
        include: '*'
endpoints:
  shutdown:
    enabled: true
  actuator:
    enabled: true



